package service.action;

public enum ActionName {

    REGISTRATION,
    LOGOUT,

    SEARCHUSER,
    SORTUSER,
    ADDUSER,
    UPDATEUSER,
    DELETEUSER,
    READUSER,
    READALLUSER,

    ADDUSERANDUSERINFO,
    UPDATEUSERANDUSERINFO,
    DELETEUSERANDUSERINFO,
    READUSERANDUSERINFO,
    READALLUSERANDUSERINFO,
    UPDATEPAGEUSERANDUSERINFO,

    ADDCAR,
    UPDATECAR,
    UPDATEPAGECAR,
    DELETECAR,
    READCAR,
    READALLCARANDORDER,
    SEARCHCAR,
    SORTCAR,


    READFULLORDERINFO,
    READALLORDER,
    MOREORDERINFO,
    UPDATEPAGEORDER,
    UPDATEORDER,
    DELETEORDER,
    ADDORDER,
    ADDORDERPAGE,
    ADDORDERWITHCUSTOMER,
    SORTORDER,
    SEARCHORDER,

    UPDATEMYSELFPAGE,
    UPDATEMYSELF,
    BLOCKUSER,
    UNBLOCKUSER,

    PRINTCHECK,
    MAINPAGE,
    PROFITANALYSIS,
    FREECARS


}
